// GENERADO por scripts/mj/process.py --emit-registry — no editar a mano.
// Fuente: scripts/mj/batches/fase-1.json + fase-4.json. Reglas de uso: docs/brand/doty-identity.md
export type DotyGroup = "expressions" | "poses" | "states" | "celebrations" | "accessories" | "themed" | "stickers" | "icons";
export type PoseEntry = { src: string; group: DotyGroup };

export const POSES = {
  feliz: { src: "/images/Doty/expressions/feliz.png", group: "expressions" },
  "muy-feliz": { src: "/images/Doty/expressions/muy-feliz.png", group: "expressions" },
  emocionado: { src: "/images/Doty/expressions/emocionado.png", group: "expressions" },
  orgulloso: { src: "/images/Doty/expressions/orgulloso.png", group: "expressions" },
  sorprendido: { src: "/images/Doty/expressions/sorprendido.png", group: "expressions" },
  pensando: { src: "/images/Doty/expressions/pensando.png", group: "expressions" },
  preocupado: { src: "/images/Doty/expressions/preocupado.png", group: "expressions" },
  triste: { src: "/images/Doty/expressions/triste.png", group: "expressions" },
  enojado: { src: "/images/Doty/expressions/enojado.png", group: "expressions" },
  decepcionado: { src: "/images/Doty/expressions/decepcionado.png", group: "expressions" },
  riendo: { src: "/images/Doty/expressions/riendo.png", group: "expressions" },
  timido: { src: "/images/Doty/expressions/timido.png", group: "expressions" },
  enamorado: { src: "/images/Doty/expressions/enamorado.png", group: "expressions" },
  cansado: { src: "/images/Doty/expressions/cansado.png", group: "expressions" },
  dormido: { src: "/images/Doty/expressions/dormido.png", group: "expressions" },
  saludando: { src: "/images/Doty/poses/saludando.png", group: "poses" },
  "pulgar-arriba": { src: "/images/Doty/poses/pulgar-arriba.png", group: "poses" },
  senalando: { src: "/images/Doty/poses/senalando.png", group: "poses" },
  "ven-aqui": { src: "/images/Doty/poses/ven-aqui.png", group: "poses" },
  bienvenido: { src: "/images/Doty/poses/bienvenido.png", group: "poses" },
  aplaudiendo: { src: "/images/Doty/poses/aplaudiendo.png", group: "poses" },
  caminando: { src: "/images/Doty/poses/caminando.png", group: "poses" },
  corriendo: { src: "/images/Doty/poses/corriendo.png", group: "poses" },
  saltando: { src: "/images/Doty/poses/saltando.png", group: "poses" },
  bailando: { src: "/images/Doty/poses/bailando.png", group: "poses" },
  sentado: { src: "/images/Doty/poses/sentado.png", group: "poses" },
  leyendo: { src: "/images/Doty/poses/leyendo.png", group: "poses" },
  escribiendo: { src: "/images/Doty/poses/escribiendo.png", group: "poses" },
  "en-laptop": { src: "/images/Doty/poses/en-laptop.png", group: "poses" },
  escuchando: { src: "/images/Doty/poses/escuchando.png", group: "poses" },
  "en-celular": { src: "/images/Doty/poses/en-celular.png", group: "poses" },
  hablando: { src: "/images/Doty/poses/hablando.png", group: "poses" },
  wow: { src: "/images/Doty/states/wow.png", group: "states" },
  "oh-no": { src: "/images/Doty/states/oh-no.png", group: "states" },
  ups: { src: "/images/Doty/states/ups.png", group: "states" },
  excelente: { src: "/images/Doty/states/excelente.png", group: "states" },
  perfecto: { src: "/images/Doty/states/perfecto.png", group: "states" },
  "sigue-asi": { src: "/images/Doty/states/sigue-asi.png", group: "states" },
  "lo-lograste": { src: "/images/Doty/celebrations/lo-lograste.png", group: "celebrations" },
  confeti: { src: "/images/Doty/celebrations/confeti.png", group: "celebrations" },
  "trofeo-celebracion": { src: "/images/Doty/celebrations/trofeo-celebracion.png", group: "celebrations" },
  medalla: { src: "/images/Doty/celebrations/medalla.png", group: "celebrations" },
  "diploma-celebracion": { src: "/images/Doty/celebrations/diploma-celebracion.png", group: "celebrations" },
  "fuegos-artificiales": { src: "/images/Doty/celebrations/fuegos-artificiales.png", group: "celebrations" },
  libro: { src: "/images/Doty/accessories/libro.png", group: "accessories" },
  lapiz: { src: "/images/Doty/accessories/lapiz.png", group: "accessories" },
  laptop: { src: "/images/Doty/accessories/laptop.png", group: "accessories" },
  tablet: { src: "/images/Doty/accessories/tablet.png", group: "accessories" },
  celular: { src: "/images/Doty/accessories/celular.png", group: "accessories" },
  mochila: { src: "/images/Doty/accessories/mochila.png", group: "accessories" },
  taza: { src: "/images/Doty/accessories/taza.png", group: "accessories" },
  diploma: { src: "/images/Doty/accessories/diploma.png", group: "accessories" },
  trofeo: { src: "/images/Doty/accessories/trofeo.png", group: "accessories" },
  microfono: { src: "/images/Doty/accessories/microfono.png", group: "accessories" },
  "bandera-uk": { src: "/images/Doty/accessories/bandera-uk.png", group: "accessories" },
  "bandera-usa": { src: "/images/Doty/accessories/bandera-usa.png", group: "accessories" },
  maleta: { src: "/images/Doty/accessories/maleta.png", group: "accessories" },
  lentes: { src: "/images/Doty/accessories/lentes.png", group: "accessories" },
  idea: { src: "/images/Doty/accessories/idea.png", group: "accessories" },
  globo: { src: "/images/Doty/accessories/globo.png", group: "accessories" },
  navidad: { src: "/images/Doty/themed/navidad.png", group: "themed" },
  halloween: { src: "/images/Doty/themed/halloween.png", group: "themed" },
  "san-valentin": { src: "/images/Doty/themed/san-valentin.png", group: "themed" },
  "fiestas-patrias": { src: "/images/Doty/themed/fiestas-patrias.png", group: "themed" },
  graduacion: { src: "/images/Doty/themed/graduacion.png", group: "themed" },
  "back-to-school": { src: "/images/Doty/themed/back-to-school.png", group: "themed" },
  "sticker-good-job": { src: "/images/Doty/stickers/good-job.png", group: "stickers" },
  "sticker-amazing": { src: "/images/Doty/stickers/amazing.png", group: "stickers" },
  "sticker-keep-going": { src: "/images/Doty/stickers/keep-going.png", group: "stickers" },
  "sticker-you-can-do-it": { src: "/images/Doty/stickers/you-can-do-it.png", group: "stickers" },
  "sticker-lets-practice": { src: "/images/Doty/stickers/lets-practice.png", group: "stickers" },
  "sticker-oops": { src: "/images/Doty/stickers/oops.png", group: "stickers" },
  "sticker-almost": { src: "/images/Doty/stickers/almost.png", group: "stickers" },
  "sticker-nice": { src: "/images/Doty/stickers/nice.png", group: "stickers" },
  "sticker-excellent": { src: "/images/Doty/stickers/excellent.png", group: "stickers" },
  "sticker-see-you": { src: "/images/Doty/stickers/see-you.png", group: "stickers" },
  taxista: { src: "/images/Doty/expressions/feliz.png", group: "poses" },
  "en-llamas": { src: "/images/Doty/expressions/en-llamas.png", group: "expressions" },
  aura: { src: "/images/Doty/expressions/aura.png", group: "expressions" },
  cocinado: { src: "/images/Doty/expressions/cocinado.png", group: "expressions" },
  "llanto-dramatico": { src: "/images/Doty/expressions/llanto-dramatico.png", group: "expressions" },
  "cerebro-galaxia": { src: "/images/Doty/expressions/cerebro-galaxia.png", group: "expressions" },
  reojo: { src: "/images/Doty/expressions/reojo.png", group: "expressions" },
  "mente-volada": { src: "/images/Doty/expressions/mente-volada.png", group: "expressions" },
  "lentes-deal": { src: "/images/Doty/expressions/lentes-deal.png", group: "expressions" },
  gamer: { src: "/images/Doty/expressions/gamer.png", group: "expressions" },
  chismoso: { src: "/images/Doty/expressions/chismoso.png", group: "expressions" },
  facepalm: { src: "/images/Doty/expressions/facepalm.png", group: "expressions" },
  flexeando: { src: "/images/Doty/expressions/flexeando.png", group: "expressions" },
  meditando: { src: "/images/Doty/expressions/meditando.png", group: "expressions" },
  bostezo: { src: "/images/Doty/expressions/bostezo.png", group: "expressions" },
  "narrador-beginner": { src: "/images/Doty/poses/narrador-beginner.png", group: "poses" },
  "narrador-intermediate": { src: "/images/Doty/poses/narrador-intermediate.png", group: "poses" },
  "narrador-advanced": { src: "/images/Doty/poses/narrador-advanced.png", group: "poses" },
} as const satisfies Record<string, PoseEntry>;

export type DotyPose = keyof typeof POSES;
export const FALLBACK_POSE: DotyPose = "feliz";

export function isDotyPose(v: unknown): v is DotyPose {
  return typeof v === "string" && Object.prototype.hasOwnProperty.call(POSES, v);
}

/** Strings dinámicos (BD, params) → pose válida o la cara amable por defecto. */
export function toDotyPose(v: string | null | undefined): DotyPose {
  return isDotyPose(v) ? v : FALLBACK_POSE;
}
